### ISSUE TITLE
Splitting channel metadata into Channel and Manifest files

### ISSUE THREAD

**Issue by jmesnil** [wildfly-extras/wildfly-channel#118]
Splitting the Channel definition into Channel and Manifest files.

Channel contains static information - repositories, vendor, etc while Manifest contains streams definition

**Comment by jmesnil** [comment]
@spyrkob can we step back from #109 and define here what we want to achieve.

In particular, we should define:

* the spec for the 2 schema (manifest and channels)
* how they relate to each other (in particular the `requires` field)
* the actual definition of the maven repositories and making sure that they can work with different environments (offline installation, proxies, etc.)

**Comment by spyrkob** [comment]
@jmesnil what's the best way to collaborate on the spec? put it down in a comment here, create a google doc?

**Comment by spyrkob** [comment]
@jmesnil I created https://github.com/wildfly-extras/wildfly-channel/pull/123 with the updated spec and schema. 

I added all the changes to the channels definition we're looking at (manifest, blocklist and default resolution strategy).
