### ISSUE TITLE
Fix link to json-schema

### ISSUE THREAD

**Issue by tommaso-borgato** [wildfly-extras/wildfly-channel#129]
https://github.com/wildfly-extras/wildfly-channel/blob/e1410ae8535470df03521700781ba21848cf8a94/core/src/main/resources/org/wildfly/channel/v1.0.0/schema.json#L3

Using online tools (https://www.liquid-technologies.com/online-schema-to-json-converter) to generate JSON from schema, you get an error unless you set:

```
"$schema": "https://json-schema.org/draft/2019-09/schema"
```

**Comment by moulalis** [comment]
@tommaso-borgato PR https://github.com/wildfly-extras/wildfly-channel/pull/131 is opened for this.
Thanks.
