### ISSUE TITLE
ChannelSession.resolveArtifact -> extension maybe null in reality cant be.

### ISSUE THREAD

**Issue by baranowb** [wildfly-extras/wildfly-channel#26]
https://github.com/jmesnil/wildfly-channel/blob/main/core/src/main/java/org/wildfly/channel/ChannelSession.java#L61
Furthermore it equates to MavenDependency.type. Not sure why its renamed, but its tad confusing.

**Comment by baranowb** [comment]
Hmm, this might be tad off, since eclipse aether does it the same way - ie. its extension, so possibly class between maven classes.

**Comment by jmesnil** [comment]
That's right, I aligned the API with `org.eclipse.aether.artifact.Artifact` that uses `extension` instead of `type`.
