### ISSUE TITLE
Ability to list the ChannelManifest and Streams  present in a ChannelSession

### ISSUE THREAD

**Issue by jfdenise** [wildfly-extras/wildfly-channel#287]
The current ChannelSession API lakes the ability to discover streams located in manifests. We need the following method:
```
public List<ChannelManifest> getManifests();
```
Allowing then to navigate to the Streams, for example:
```
for (ChannelManifest manifest : session.getManifests()) {
  for (Stream stream : manifest.getStreams()) {
...
```

**Comment by spyrkob** [comment]
@jfdenise I'm not sure on the use case, but the channel session can resolve artifacts not listed in the streams (via `resolve-if-no-stream`), so if the goal is to list artifacts that can be resolved, this might not be enough

**Comment by jfdenise** [comment]
@spyrkob , the goal is to get the streams that are configured in the set of channel manifests. No dynamic resolution is needed.
