### ISSUE TITLE
Ability to retrieve version of the manifest (if Maven manifest) use by the session

### ISSUE THREAD

**Issue by TomasHofman** [wildfly-extras/wildfly-channel#292]
In case manifest coordinates given to ChannelSession are Maven GA coordinates, prospero might be interested in knowing what is the actual resolved version of the manifest(s).

The use case is that during the update operation, prospero would compare current and target versions of the manifest(s), and refused the update operation (or requested further confirmation) if the update constitutes a downgrade to an earlier manifest version.

Cc @spyrkob for your review too.

**Comment by KERERCVASD** [comment]
I think this will help you.
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive
