### ISSUE TITLE
Versioning of channels yaml

### ISSUE THREAD

**Issue by vsalbaba** [wildfly-extras/wildfly-channel#56]
In the event of changes to channel yaml specification, it might be a good idea to start versioning the specification and keep intended specification version in the yaml file. That way we can better ensure backwards compatibility.

**Comment by jmesnil** [comment]
Tha's a good suggestion, we could add some versioning to the [specification](https://github.com/wildfly-extras/wildfly-channel/blob/main/doc/spec.adoc) and the [JSON schema](https://github.com/wildfly-extras/wildfly-channel/blob/main/core/src/main/resources/org/wildfly/channel/channel-schema.json) (that is authoritative).

However I'm not sure how to put this information into the channel YAML file...

**Comment by vsalbaba** [comment]
I'd suggest:
- adding schema versioning guidelines to the specification doc, I would say SchemaVer looks as a sane and readable solution:
https://snowplowanalytics.com/blog/2014/05/13/introducing-schemaver-for-semantic-versioning-of-schemas

> Given a version number MODEL-REVISION-ADDITION, increment the:
> 
> MODEL when you make a breaking schema change which will prevent interaction with any historical data
> REVISION when you make a schema change which may prevent interaction with some historical data
> ADDITION when you make a schema change that is compatible with all historical data

- incorporate schema version into $id attribute, like so:
`"$id": "https://wildfly.org/v1.0.0/channel.schema.json"`
- add schemaVersion property to the schema
```
"properties": {
...
    "schemaVersion": {
      "description": "The version number of the schema in model.revision.addition format. ",
      "type": "string",
      "pattern": "^[0-9]{1,}.[0-9]{1,}.[0-9]{1,}$"
    },
...
 }
```
