### ISSUE TITLE
Support for "newest" stream version

### ISSUE THREAD

**Issue by vsalbaba** [wildfly-extras/wildfly-channel#76]
In the `spec.adoc`, we have a requirement that in the `streams` section, either the `version` or the `versionPattern` field must be used.

I propose allowing neither to be present, and in that case resolving to the "newest" version of a stream. This is equivalent to specifying `versionPattern: '.*'`

This would be analogous to how the `requires` section behaves to channel requirements with a missing `version` field.

**Comment by jmesnil** [comment]
-1, we want to limit the use of Maven metadata to the minimum.
Channels are a curated list of components and it's up to its author to curate it.

 As you mention, the behaviour you want to have (get whatever is the latest version) is already obtainable using the `versionPattern: '.*'`.
