### ISSUE TITLE
Required channel load order 

### ISSUE THREAD

**Issue by vsalbaba** [wildfly-extras/wildfly-channel#81]
Specification says that 

> The channels will be searched for a stream that matches the groupId/artifactId of the artifact. If the channel requires other channels, these will be searched first in their listed order.
> 
> The first stream that is found matching the groupId/artifactId will be used to determine the version of the artifact to pull. 

This implies that when multiple channels are required and they all stream the same artifact, the version of the artifact from the first defined stream (according to order in `streams` section) should be used.

But according to tests. it seems that the newest version of the artifact is used instead.

```
org.opentest4j.AssertionFailedError: 
Expected :1.2.0.Final
Actual   :2.0.0.Final
...
	at org.wildfly.channel.ChannelWithRequirementsTestCase.testChannelMultipleRequirements(ChannelWithRequirementsTestCase.java:444)
...
```

Related tests added in https://github.com/wildfly-extras/wildfly-channel/pull/80

**Comment by jmesnil** [comment]
I think the code is correct but the Javadoc needs to be updated.

When a channel requires multiple channels that defines different version of the same artifact, it is correct to use the latest one.

Your `required-channel-1` defines `org.foo:bar:1.2.0.Final` and your `required-channel-2` defines `org.foo:bar:2.0.0.Final`.
If you ends up using `1.2.0.Final`, you are breaking the code that needs `2.0.0.Final`.

We should change the doc to:

```
The channels will be searched for a stream that matches the groupId/artifactId of the artifact.

Channels are searched in their listed orders.
If a channel directly defines a stream that matches the groupId/artifactId of the artifact, the version will be resolved from this stream.
If a channel requires other channels, the latest version from its required channels will be used.
```

wdyt?

**Comment by vsalbaba** [comment]
I think that when we are using the latest, we do not have to specify in which order the requried channels will be searched. They can be searched in any order and it should not change the result.

I propose
```
The channel will be searched for a stream that matches the `groupId`/`artifactId` of the artifact.

If the channel directly defines a stream that matches the groupId/artifactId of the artifact, the version will be resolved from this stream.

If the channel does not directly define a stream, required channels will be searched and the latest version of the stream found will be used.
```

**Comment by vsalbaba** [comment]
I've updated the https://github.com/wildfly-extras/wildfly-channel/pull/80 MR

**Comment by jmesnil** [comment]
> Channels are searched in their listed orders.

This sentence must stay. It's not about "required channels" order, it's about "channels" order  (because you can multiple channels).

The order of the channels is significant (when you specify multiple channels).
The order of *required* channels inside a channel is not significant (we will take the latest version).
