### ISSUE TITLE
Streams for artifacts with classifiers

### ISSUE THREAD

**Issue by spyrkob** [wildfly-extras/wildfly-channel#82]
Right now Stream is identified by `groupId` and `artifactId` only. This means that eg. `org.wildfly.core:wildfly-cli` and `org.wildfly.core:wildfly-cli:client` will always be on the same version and when one is updated, the other one has to be released as well. 
Should those two represent two different streams or one stream?

**Comment by jmesnil** [comment]
This could be an improvement for future versions but I think using the same version for all classifier/extensions of the same `groupId:artifactId` makes most sense. After all, all these classifiers have to be released together anyway.

**Comment by spyrkob** [comment]
Resolving as defered
