### ISSUE TITLE
Parralel resolution of available versions

### ISSUE THREAD

**Issue by TomasHofman** [wildfly-extras/wildfly-channel#89]
Currently when using open channels (versions are specified by `versionPattern`), lot of time is spend on resolving available versions.

For demonstration, it takes about 30 seconds to provision wildfly-core (measured when all artifact files were already present in local maven cache). Of these 30 seconds, more then 20 seconds is spent in the `ChannelSession#splitArtifactsPerChannel()` method which performs the versions request to remote maven repositories (=> large number of http requests to obtain repository metadata).

I tried a simple experiment where the versions were resolved in a parallel stream using 10 threads. This reduced the installation time from 30 seconds to 10 seconds. The version resolution work now takes only around 2-3 seconds.

Can the channel library do parallel version resolution?

**Comment by jmesnil** [comment]
that's a good improvement. We could refactor the code to use a `parallelStream`. @TomasHofman do you want to do it?

**Comment by TomasHofman** [comment]
Yes, I will submit a PR.
